# Generated by Django 5.0.6 on 2024-05-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=4.5)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('company', models.CharField(choices=[('Carlton London', 'Carlton London'), ('CUKOO', 'CUKOO'), ('TELLY', 'TELLY'), ('Unknown', 'Unknown')], default='Unknown', max_length=100)),
                ('discount_percentage', models.PositiveIntegerField(default=1)),
                ('original_price', models.PositiveIntegerField(default=1)),
                ('return_perion', models.PositiveIntegerField(default=14)),
                ('delivary_date', models.DateTimeField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='app.rating')),
            ],
        ),
    ]
