# Generated by Django 5.0.6 on 2024-05-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_return_perion_product_return_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.PositiveIntegerField(default=4.5),
        ),
        migrations.DeleteModel(
            name='rating',
        ),
    ]
