# Generated by Django 5.0.6 on 2024-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_rating_product_count_product_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.FloatField(default=4.5),
        ),
    ]
